name: Deploy GoshehArtWebApp to (Staging)

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["8.0.x"]

    env:
      DOTNET_ENVIRONMENT: Staging
      ASPNETCORE_ENVIRONMENT: Staging
      CONNECTION_STRING_STAGING: ${{ secrets.CONNECTION_STRING_STAGING }}
      ADMIN_PASSWORD_STAGING: ${{ secrets.ADMIN_PASSWORD_STAGING }}

    steps:
      - uses: actions/checkout@v2

      - name: Set HOME environment variable
        run: |
          echo "HOME=/home/runner" >> $GITHUB_ENV

      - name: Setup .NET Core SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release -o /var/www/goshehartwebapp-staging/

      - name: Deploy with PM2
        run: |
          export PM2_HOME=/root/.pm2
          
          export DOTNET_ENVIRONMENT="$DOTNET_ENVIRONMENT"
          export ASPNETCORE_ENVIRONMENT="$ASPNETCORE_ENVIRONMENT"
          export ADMIN_PASSWORD="$ADMIN_PASSWORD"
          export CONNECTION_STRING="$CONNECTION_STRING"
          export SMTP_HOST="$SMTP_HOST"
          export SMTP_USERNAME="$SMTP_USERNAME"
          export SMTP_PASSWORD="$SMTP_PASSWORD"
          export SMTP_FROM="$SMTP_FROM"
          export SMTP_PORT="$SMTP_PORT"
          
          pm2 stop goshehartwebapp-staging || true
          pm2 start /var/www/goshehartwebapp-staging/GoshehArtWebApp.dll \
            --name goshehartwebapp-staging \
            --interpreter dotnet \
            --env DOTNET_ENVIRONMENT="$DOTNET_ENVIRONMENT" \
            --env ASPNETCORE_ENVIRONMENT="$ASPNETCORE_ENVIRONMENT" \
            --env ADMIN_PASSWORD="$ADMIN_PASSWORD" \
            --env CONNECTION_STRING="$CONNECTION_STRING" \
            --env SMTP_HOST="$SMTP_HOST" \
            --env SMTP_USERNAME="$SMTP_USERNAME" \
            --env SMTP_PASSWORD="$SMTP_PASSWORD" \
            --env SMTP_FROM="$SMTP_FROM" \
            --env SMTP_PORT="$SMTP_PORT"
            
            pm2 save

      - name: Nginx Restarting
        run: service nginx reload
