name: Deploy GoshehArtWebApp to Staging

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["8.0.x"]

    env:
      DOTNET_ENVIRONMENT: Staging
      ASPNETCORE_ENVIRONMENT: Staging
      CONNECTION_STRING: "${{ secrets.CONNECTION_STRING_STAGING }}"
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD_STAGING }}
      Smtp__Host: ${{ secrets.SMTP_HOST }}
      Smtp__Username: ${{ secrets.SMTP_USERNAME }}
      Smtp__Password: ${{ secrets.SMTP_PASSWORD }}
      Smtp__From: ${{ secrets.SMTP_FROM }}
      Smtp__Port: ${{ secrets.SMTP_PORT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set HOME environment variable
        run: echo "HOME=/home/runner" >> $GITHUB_ENV

      - name: Setup .NET SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o /var/www/goshehartwebapp-staging
      - name: Deploy with PM2
        run: |
          export PM2_HOME=/root/.pm2
      
          # Stop previous instance
          pm2 stop goshehartwebapp-staging || true
      
          # Start new instance with proper env vars (note double underscores)
          pm2 start /var/www/goshehartwebapp-staging/GoshehArtWebApp.dll \
            --name goshehartwebapp-staging \
            --interpreter dotnet \
            --env DOTNET_ENVIRONMENT="Staging" \
            --env ASPNETCORE_ENVIRONMENT="Staging" \
            --env CONNECTION_STRING="${{ secrets.CONNECTION_STRING_STAGING }}" \
            --env ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD_STAGING }}" \
            --env Smtp__Host="${{ secrets.SMTP_HOST }}" \
            --env Smtp__Username="${{ secrets.SMTP_USERNAME }}" \
            --env Smtp__Password="${{ secrets.SMTP_PASSWORD }}" \
            --env Smtp__From="${{ secrets.SMTP_FROM }}" \
            --env Smtp__Port="${{ secrets.SMTP_PORT }}"
      
          # Save PM2 config so it persists across restarts
          pm2 save


      - name: Reload Nginx
        run: sudo service nginx reload
