name: Deploy GoshehArtWebApp to Staging

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["8.0.x"]

    env:
      DOTNET_ENVIRONMENT: Staging
      ASPNETCORE_ENVIRONMENT: Staging
      CONNECTION_STRING: "${{ secrets.CONNECTION_STRING_STAGING }}"
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD_STAGING }}
      Smtp__Host: ${{ secrets.SMTP_HOST }}
      Smtp__Username: ${{ secrets.SMTP_USERNAME }}
      Smtp__Password: ${{ secrets.SMTP_PASSWORD }}
      Smtp__From: ${{ secrets.SMTP_FROM }}
      Smtp__Port: ${{ secrets.SMTP_PORT }}

    steps:
      - uses: actions/checkout@v3

      - name: Set HOME environment variable
        run: echo "HOME=/home/runner" >> $GITHUB_ENV

      - name: Setup .NET SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish app
        run: dotnet publish -c Release -o /var/www/goshehartwebapp-staging/

      - name: Deploy with PM2
        run: |
          export PM2_HOME=/root/.pm2
      
          export DOTNET_ENVIRONMENT="$DOTNET_ENVIRONMENT"
          export ASPNETCORE_ENVIRONMENT="$ASPNETCORE_ENVIRONMENT"
          export ADMIN_PASSWORD="$ADMIN_PASSWORD"
          export CONNECTION_STRING="$CONNECTION_STRING"
          export Smtp__Host="$Smtp__Host"
          export Smtp__Username="$Smtp__Username"
          export Smtp__Password="$Smtp__Password"
          export Smtp__From="$Smtp__From"
          export Smtp__Port="$Smtp__Port"
      
          pm2 stop goshehartwebapp-staging || true
          pm2 start /var/www/goshehartwebapp-staging/GoshehArtWebApp.dll \
            --name goshehartwebapp-staging \
            --interpreter dotnet \
            --env DOTNET_ENVIRONMENT="$DOTNET_ENVIRONMENT" \
            --env ASPNETCORE_ENVIRONMENT="$ASPNETCORE_ENVIRONMENT" \
            --env ADMIN_PASSWORD="$ADMIN_PASSWORD" \
            --env CONNECTION_STRING="$CONNECTION_STRING" \
            --env Smtp__Host="$Smtp__Host" \
            --env Smtp__Username="$Smtp__Username" \
            --env Smtp__Password="$Smtp__Password" \
            --env Smtp__From="$Smtp__From" \
            --env Smtp__Port="$Smtp__Port"
      
          pm2 save


      - name: Reload Nginx
        run: sudo service nginx reload
