# Triggers
name: Deploy GoshehArtWebApp to (Production)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        dotnet: ["8.0.x"]

    steps:
      - uses: actions/checkout@v2

      - name: Set HOME environment variable
        run: |
          echo "HOME=/home/runner" >> $GITHUB_ENV

      - name: Setup .NET Core SDK ${{ matrix.dotnet }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Install dependencies
        run: dotnet restore

      - name: Check Environment Variable
        run: |
          if [ -z "$DOTNET_ENVIRONMENT" ] || [ "$DOTNET_ENVIRONMENT" != "Production" ]; then
            export DOTNET_ENVIRONMENT=Production
            echo "DOTNET_ENVIRONMENT set to Production."
          else
            echo "DOTNET_ENVIRONMENT is already set to $DOTNET_ENVIRONMENT."
          fi

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: |
          dotnet publish -c Release -o /var/www/goshehartwebapp/_work/GoshehArtWebApp/GoshehArtWebApp

      - name: PM2 Syncing for Production
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          export PM2_HOME=/root/.pm2
          pm2 stop goshehartwebapp || true
          pm2 start /var/www/goshehartwebapp/_work/GoshehArtWebApp/GoshehArtWebApp/GoshehArtWebApp.dll \
            --name goshehartwebapp \
            --interpreter dotnet \
            --env DOTNET_ENVIRONMENT=Production \
            --env CONNECTION_STRING="$CONNECTION_STRING" \
            --env ADMIN_PASSWORD="$ADMIN_PASSWORD"
          pm2 save

      - name: Nginx Restarting
        run: service nginx restart
